name: Build `examples/java` pushes

on:
  push:
    paths:
      - "examples/java/**"
      - ".github/workflows/examples-java-push.yml"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: examples/java
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: ./gradlew clean build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: examples-java-libs
          path: '**/build/libs/*'
          retention-days: 5
      - name: Upload Test reports
        uses: actions/upload-artifact@v2
        with:
          name: examples-java-reports
          path: '**/build/reports/*'
          retention-days: 5
