name: Test OpenAPI doc is valid (Push)

on:
  push:
    paths:
      - '.github/workflows/openapi-docs-push.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"
jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: 'v1alpha/openapi.yml'
          spectral_ruleset: 'schemas/.spectral.yml'
