name: Test OpenAPI doc is valid (Push)

on:
  push:
    paths:
      - '.github/workflows/openapi-docs-push.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"
      - "schemas/package.json"

permissions:
  contents: read

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schemas
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      - run: npm install
      - run: npm run lint:oas
