name: Test OpenAPI doc is valid (Push)

on:
  push:
    paths:
      - '.github/workflows/openapi-docs-push.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"

permissions:
  contents: read

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schemas
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd
      - run: npm install
      - run: npm run lint:oas
