name: Test OpenAPI doc is valid (Push)

on:
  push:
    paths:
      - '.github/workflows/openapi-docs-push.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"
jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schemas
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint:oas
