name: Test OpenAPI doc is valid on Pull Requests

on:
  pull_request:
    paths:
      - '.github/workflows/openapi-docs-pr.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"
      - "schemas/package.json"

permissions:
  contents: read

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schemas
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      - run: npm install
      - run: npm run lint:oas
