name: Test schemas are valid (Pull Request)

on:
  pull_request:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      - run: npm install
      - run: npm run test
