name: Test schemas are valid (Pull Request)

on:
  pull_request:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      - run: npm install
      - run: npm run test
