name: Test schemas are valid (Pull Request)

on:
  pull_request:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
      - run: npm install
      - run: npm run test
