name: Test schemas are valid (Push)

on:
  push:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
      - run: npm install
      - run: npm run test
