name: Test schemas are valid (Pull Request)

on:
  pull_request:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
      - run: npm install
      - run: npm run test
