name: Test schemas are valid (Push)

on:
  push:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      - run: npm install
      - run: npm run test
